name: Shop React CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'shopizer-shop-reactjs/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'shopizer-shop-reactjs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: 'shopizer-shop-reactjs/package-lock.json'

      - name: Install dependencies
        working-directory: shopizer-shop-reactjs
        run: npm install

      - name: Build
        working-directory: shopizer-shop-reactjs
        run: npm run build

      - name: Run Tests
        working-directory: shopizer-shop-reactjs
        run: npm test -- --watchAll=false
        env:
          CI: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: shop-react
          path: shopizer-shop-reactjs/build/
